language: matlab
matlab:
  - R2020b
script: matlab -batch "addpath(genpath(pwd)); results = runtests('IncludeSubfolders',true); assertSuccess(results);"
after_success: bash <(curl -s https://codecov.io/bash)
